### ISSUE TITLE
User story #1 - Single source of truth 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/registry#1]
As 360Giving I want the registry to be the single source of truth so we can validate against it.

**Comment by robredpath** [comment]
@morchickit what does validation look like in this context?

**Comment by morchickit** [comment]
Meaning other applications can check against it.

**Comment by robredpath** [comment]
Can you give me an example of what that might look like? I'm struggling to see how this is different from just being machine-readable

**Comment by morchickit** [comment]
How is machine readable connects to it?

This is a concept - we want one place where people know who publish to
360Giving that they can validate it against their data. All the files that
are published, so if one of the files they have is not in the registry
list, it means it's not a 360Giving file.
