### ISSUE TITLE
Make heatmap colour-code key refer only to itself

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/registry#116]
Some publishers have lots of grants, and so the heatmap isn't very useful - there can be a lot of variation, but they're all the same colour:

<img width="921" alt="Screenshot 2022-07-11 at 16 14 16" src="https://user-images.githubusercontent.com/641009/178297551-cfb663da-90ea-4480-95f0-2bf6a6ec66d7.png">
 
The same applies, although less so, to publishers with very low numbers of grants:
<img width="932" alt="Screenshot 2022-07-11 at 16 14 46" src="https://user-images.githubusercontent.com/641009/178297623-0729af2f-3dc1-4e4d-8f33-5b7a384e740f.png">

**Comment by mariongalley** [comment]
@Lathrisk While you're working on the heatmap, this might be one to look at - I think this works in the Individual publisher view, but in the list view would it be confusing that the scale is different on a publisher by publisher basis?

**Comment by Lathrisk** [comment]
@mariongalley agreed, I think when we initially did this work we used the bandings to give a consistent comparison across publishers in the list view. I'll have a look at changing this for the publisher view and see if I can find any improvements for the list view while I'm there.

**Comment by mariongalley** [comment]
@KDuerden Does that sound reasonable? I think we reviewed all these and do want them to happen but let me know if you'd rather we left it as is.

**Comment by mariongalley** [comment]
Comment from Katherine:
> I think it needs to be consistent in both views. The heatmap won't be that meaningful for a publisher that has a very consistent number of grants awarded (& published) but I have thought of the key goal of the heatmap being to show 'the periods is data available for'. As long as the chart helps to highlight if/when there is a drop off, as well as indicating when a funder started to publish, I think it is doing its job.

On that basis I'm happy to close this unless you have any thoughts on making the heatmap more meaningful that don't result in the individual view being different to the list view @Lathrisk ?

**Comment by KDuerden** [comment]
Thanks both. What are the thresholds for the shades based on? Maybe there could be an improvement in that which would make the difference between funders of different scales more obvious (and ensure drop-offs are clear).

**Comment by Lathrisk** [comment]
@mariongalley @KDuerden I'll have a think about some options. Perhaps we could create some visual distinction between grants that are in the range 1-100, 100-1000, and those that are 1000+. This could be colours or borders, or something to that effect. I think we'd want to keep it simple and intuitive though.

At the moment anything >100 has the same opacity (the opacity is calculated by `grants/100` for a value between 0 and 1. IIRC this was because most publishers have grants in the range of 0-100. It also means that a publisher with 78k grants (e.g. Cabinet office) is represent the same as a publisher with 100 grants in a single year.

**Comment by KDuerden** [comment]
Great. I did some quick analysis on grants in 2019 and 2020, and it breaks down as follows (sorry couldn't work out how to paste actual table into here!)

![image](https://user-images.githubusercontent.com/20462640/181495978-53326949-5c01-4c18-93f6-7b8986f1f0d6.png)

Those bands might not be perfect but would that give more variation?

**Comment by mariongalley** [comment]
Yeah, how many bands do we have to play with total? I'd be comfortable with those 4 bands in the 100+ range and then an extra 4-6 bands in the 0-100 range to still show variance for the majority that are in that range?

**Comment by KDuerden** [comment]
What about this? 

![image](https://user-images.githubusercontent.com/20462640/181500961-e17c5b06-46f5-4a9c-bb23-64bede386f32.png)

**Comment by mariongalley** [comment]
That looks good to me. Up to 25 would be the lightest orange, with 0 being completely white so you can still see when no data was published at all.

**Comment by Lathrisk** [comment]
I've attached a selection based on the [bandings above](https://github.com/ThreeSixtyGiving/registry/issues/116#issuecomment-1198054440). I think this extended range gives a much clearer indication of the relative differences. Again, these bandings are easy to adjust if we want to make any changes.

![AB-Heatmap](https://user-images.githubusercontent.com/517804/181549157-5be0f15a-1f08-4044-abbc-04b7e1b672b1.png)
![BBC-Heatmap](https://user-images.githubusercontent.com/517804/181549179-9e9c5eed-4c4b-4e3e-bc87-f8281650426f.png)
![Cabinet-Heatmap](https://user-images.githubusercontent.com/517804/181549190-f55ae821-aca3-45d8-b5fe-4770940e7f2b.png)
![City-Heatmap](https://user-images.githubusercontent.com/517804/181549199-717db1aa-0f1f-4b66-8f86-226515ac4436.png)

**Comment by mariongalley** [comment]
Thanks Jared, I'm really happy with that

**Comment by KDuerden** [comment]
Me too!

**Comment by Lathrisk** [comment]
This has now been deployed.
