### ISSUE TITLE
Include Publisher Logos on Publisher Dashboard

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/registry#118]
This is required to satisfy [#115](https://github.com/ThreeSixtyGiving/registry/issues/115)

**Comment by KDuerden** [comment]
My preferred placing would be right aligned at the same level as the publisher name, on the publisher detail page.

![image](https://user-images.githubusercontent.com/20462640/182826423-bd2ff91e-0dfd-439e-97e8-c09dcacfacfa.png)

This would mean the publisher list would not have the logo showing, but as the design doesn't really allow for adding an image, I think that is ok.

**Comment by mariongalley** [comment]
@codemacabre This is fixed in dev, thank you
