### ISSUE TITLE
User story #12 - Metadata

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/registry#12]
As a data analyst I want to know the meta data of a file so I will know if the file is relevant for me or not. 

As a data analyst I want the meta-data to be synced with the data so I can trust it.

**Comment by stevieflow** [comment]
I would suggest that this is too broad a topic for a single issue.  We're talking about many different types of metadata - centrally maintained; in-file; dervied; status - so this story will be difficult to pinpoint

**Comment by morchickit** [comment]
Ok, refining this - 
- As A data analyst I would like to know the publisher's **name**, so I will know if it is relevant for me. 
- As A re-user I would like to know the file's **license**, so I will know how can I use it.
- As a data analyst I want to know how many **grants (lines)** in a file so I can validate that I have downloaded all the data. 
- As a data analyst I want to know the file **size** so I will know how to process it. 
- As a data analystI want to know the **file format** so I will know how to process it. 
- As a data analyst I want to know the grants period so I can understand if this file is relevant for my work. 
- As a user I want to know the *file name* so I can understand if it is relevant for me. 
- As a data analyst I want to know if the file is valid so I can join it with other files. 

Note, this is not for the whole meta data file, this is only for the table that is the registry.
