### ISSUE TITLE
User story #13 - URL access

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/registry#13]
As 360Giving we want publishers to register the data URL so others can access that data.

**Comment by stevieflow** [comment]
Via the data.json file we have two URLs:

- ``downloadURL``: A valid URL to directly access the data 
- ``accessURL``: A valid URL, usually to a web page, where access to the downloadURL can be found. The web page usually has other useful information about the data | 

I think we want publishers to register *both* of these URLs?

**Comment by morchickit** [comment]
Yes.
