### ISSUE TITLE
Link to Data File Submission (DQT) from Publisher page in Quality Dashboard

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/registry#135]
Given that the primary audience for the Quality Dashboard is Publishers, we're starting to conceive of it as a One-stop-shop for all the important information and links they need in relation to 360Giving. We've already got their GrantNav link there, an Insights link coming soon, and links to all their data files/licence details. It would be really helpful to add a Call To Action in relation to their files that directs them to the Data File Submission process in the Data Quality Tool if they want to update their file.

Copy/Design TBC, but just adding this so we remember to give it some thought.

**Comment by mariongalley** [comment]
@codemacabre @KDuerden I'd suggest we add the link to the Data File Submission within the Datasets card that contains all the current registry links. If we do that, it might make sense to move the GrantNav & Insights links to within the Total grants published card too. What do you think?

![image](https://github.com/ThreeSixtyGiving/registry/assets/82958988/be5ec28a-e4b8-42c3-b95b-018c6876d9a0)

**Comment by codemacabre** [comment]
Looks good to me, @mariongalley. Is the URL for the 'Update your data' link, https://dataquality.threesixtygiving.org/ ?

**Comment by mariongalley** [comment]
@codemacabre Yes update your data should link to the DQT. Happy for it to be the same colour as GrantNav and Insights - I just made it teal in case my MS-Paint job was so seamless you couldn't see what I'd changed 😄

**Comment by codemacabre** [comment]
Deployed!
