### ISSUE TITLE
User story #14 - Contact details

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/registry#14]
As 360Giving we want publishers to register their contact details so we can inform them about issues in the future. 

As a publisher staff I want the contact data in the register to be associated with an organisation, not a person, so my privacy will remain.

**Comment by stevieflow** [comment]
Is this a request that contact details for each publisher are published openly in the registry?  I would imagine there would have to be close control of this data (via 360 Salesforce?) to ensure that a) no personal data is disclosed accidentally b) that the contact details are current and c) that someone at the end of the line knows what to do if someone contacts them (often overlooked)

Also, we do want to include the ``accessURL`` alongside the ``downloadURL``, so we could/should consider that the definitive contact details could actually be best maintained by the publisher on their own site (as we prefer with data access).  

@KDuerden will have ideas too

**Comment by KDuerden** [comment]
This reads like an attempt to re-produce related things which we already have: 

Our Salesforce, which currently maintains the registry has organisation records which have data distributions and contacts records related to it. This is privately and securely held by 360Giving, and used when we need to contact publisher about their data.

GrantNav includes access url which signposts to where further info/Qs about data can be asked. This does not include any personal data.
