### ISSUE TITLE
Rename individuals codelists badge

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/registry#146]
Rename the badge from "Includes recipient individual grantPurpose or primaryGrantReason codes" to "Includes grants to individuals codes"

**Comment by michaelwood** [comment]
Copy location - https://github.com/ThreeSixtyGiving/registry/blob/dashboard/registry-vue/src/components/publishers/data/badges.js#L50

**Comment by codemacabre** [comment]
Deployed to live!

**Comment by codemacabre** [comment]
Deployed to live!
