### ISSUE TITLE
Include count of publishers when filters are applied

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/registry#149]
We would like to include a count of the number of publishers when a selection has been made.

At the moment it is hard to see how significant some of the things are eg: https://qualitydashboard.threesixtygiving.org/publishers?badges=hasGrantDuration&badgeSelection=include - but gets more complicated if there are multiple filters selected and you then can't use any of the stats on the "all" page.

Related to #75

**Comment by codemacabre** [comment]
@mariongalley How do you envision this to look? We could add it as a stat, but then we'd probably need to either remove or update the remaining stats to match the filtered data. Or we could add it as an inline heading / text?

**Comment by mariongalley** [comment]
@codemacabre The inline version is ideal, thank you!
