### ISSUE TITLE
User story #15 - Unique prefix

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/registry#15]
As 360Giving publishers support, I want to register the unique publishers prefix so we can make sure they are unique

**Comment by robredpath** [comment]
@KDuerden is there currently a list of prefixes anywhere?

**Comment by KDuerden** [comment]
Yes, stored in Salesforce. The field validates to ensure it is unique.

This is used to populate the prefix value on the GrantNav publisher pages, so I assume gets pulled into JSON version of the Registry.
