### ISSUE TITLE
Update link for developer documentation

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/registry#17]
@BibianaC 

> Developers: For a JSON feed of published datasets visit http://data.threesixtygiving.org

For the new page, please can we change this to 

> Developers: For a JSON feed of published datasets visit http://standard.threesixtygiving.org/en/latest/getdata/

cc/ @morchickit

**Comment by BibianaC** [comment]
@stevieflow This issue can be close, right?

**Comment by stevieflow** [comment]
Yep.  Thanks
