### ISSUE TITLE
Insert the count of the number of publishers into the text

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/registry#18]
There are probably a couple of ways to this- but anyway:

> More than 70 organisations are publishing grants data to the 360Giving open data standard.

The count here could / should be actual

**Comment by BibianaC** [comment]
The count has been updated in the commit:
https://github.com/ThreeSixtyGiving/registry/pull/16/commits/d37148d0ea039902df39f18f2bc1b185b823545d

**Comment by BibianaC** [comment]
Sorry, I misunderstood the issue (from manual to automatic)

**Comment by KDuerden** [comment]
I know that automatic count is under consideration at the moment. In the meantime can you update to 
"More than 90 organisations are publishing grants data to the 360Giving open data standard."
Once we get to 'over 100' we might be able to call it a day on updating this anyway. Let's discuss.
