### ISSUE TITLE
Create dev version of registry to use new fields + update as more fields become available

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/registry#20]

**Comment by BibianaC** [comment]
@robredpath 
As per `Support #14732 ticket` I understand that the new fields to be added in the Registry will be:

No. of awards
Total amount awarded
No. of recipients
First award date
Last award date
No. of funders

**Comment by robredpath** [comment]
Initially, yes, but we're aiming towards the list in https://github.com/ThreeSixtyGiving/test_registry/issues/5 over the course of these couple of sprints

**Comment by BibianaC** [comment]
Done
