### ISSUE TITLE
Display a licence icon - but only for acceptable licences?

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/registry#22]
In the metadata we have:

- licence - the specific licence applied to the publication
- acceptable licence - whether this licence permits reuse (we need to pull out our criteria for this) 

We've noted that we like approaches such as Open Active that display the licence icon, rather than the text name 
 
![licence](https://user-images.githubusercontent.com/1209944/42866880-cd998a84-8a65-11e8-984b-3bcda63e8e00.png)

[ I assume this is via something like https://licensebuttons.net/ ]

In the initial view of registry records, we could look to display licence icons.  But - what happens if someone chooses a licence that is "unacceptable"?

Maybe an easier path is that we have one "column" for the licence display.:

- If an acceptable licence from [list] we display icon and include link
- If licence is unacceptable, then we display a [red x]

(Strictly, this isn't true - as an unacceptable licence is still a licence)

At the header of the column we include a tooltip or link to explanation of licencing and our rationale for acceptable

And, or course, we include this, for @Bjwebb : https://www.youtube.com/watch?v=07So_lJQyqw

**Comment by BibianaC** [comment]
Done
