### ISSUE TITLE
Hardcode big lottery file data?

### ISSUE THREAD

**Issue by Bjwebb** [ThreeSixtyGiving/registry#28]
Splitting this out into its own pull request, because there's already quite a bit of back and forth about other issues in the PR.

From https://github.com/ThreeSixtyGiving/registry/pull/23#issuecomment-410667302:

> we should hard-code the values for the massive Big Lottery file, rather than leaving them blank. My preference is that we do this in the daily test code (cc @Bjwebb ) but I think an acceptable workaround is to hardcode it in this repo if it's complicated or will take time to do it there (or we don't want to, for a reason I've not thought of)

**Comment by BibianaC** [comment]
@Bjwebb what do you think about it? can you hardcode it in the json file?

**Comment by Bjwebb** [comment]
I don't like the idea of simply hardcoding it in the python code. I'm looking into whether we can use a fallback JSON file from a manual run, either by:
* Commiting it to the repo - in the case I'd rather ensure the JSON is only the datasets the regular run will miss
* Downloading it from a URL - this is possibly something we could expose for the data capture used for GrantNav

**Comment by Bjwebb** [comment]
D'oh, accidentally pushed this to the master branch: https://github.com/ThreeSixtyGiving/datagetter/commit/70c3d9303a1a5743346ca12d09cd70bb4cc96180
It does mean that once the build finishes the Big Lottery info will show up on the registry.

**Comment by BibianaC** [comment]
thanks @Bjwebb ! It does show up in the registry now.
