### ISSUE TITLE
What is the order of records when a publisher has more than one?

### ISSUE THREAD

**Issue by stevieflow** [ThreeSixtyGiving/registry#40]
Take a look at the big lottery:

![data registry 360giving 1](https://user-images.githubusercontent.com/1209944/49028632-bc3a6000-f19a-11e8-85ab-975c8b9b5a76.png)

It isn't clear how this order is generated.  @BibianaC please can you clarify?  We can then discuss if we want to alter this

Observed by @KDuerden

**Comment by KDuerden** [comment]
@robredpath I don't understand - 'sort by the date of the first grant in the file'
First means what? Most recently awarded grant or the first to be awarded (eg oldest)? Top in the file? 
And this will apply across several files so - 'first' based on all the grants in all the files for a particular publisher?

**Comment by BibianaC** [comment]
@KDuerden the table will be sorted by publisher name (as it is now) and if the publisher has more than one grant, these ones will be sorted by year (based on the min_award_date field).
<img width="1137" alt="screen shot 2018-11-29 at 15 48 09" src="https://user-images.githubusercontent.com/9610927/49233648-55ad8000-f3ee-11e8-8b91-5780528b4405.png">

**Comment by KDuerden** [comment]
@BibianaC thanks for clarifying. We need it to be the opposite - ordered by max_award_date field
This will be most helpful for the cases of name change - which is what prompted this ticket - as outlined the GN behaviour [here](https://github.com/OpenDataServices/grantnav/issues/409#issuecomment-440721832)

**Comment by BibianaC** [comment]
@KDuerden I can change it to max_award_date. Do this mean that you also want it in reverse order? The newest first? In the case of the Big Lottery the first to be 'Big Lottery Fund - grants data 2018-19 year-to-date'?

**Comment by KDuerden** [comment]
Yes the most recent first please.

**Comment by BibianaC** [comment]
@KDuerden I have done the change. Thanks for the feedback.

**Comment by KDuerden** [comment]
The order of files on the Registry doesn't seem to be sorted by year based on the max_award_date field. 
Has this change not been push to live? I'm sure I had seen this happen.

**Comment by robredpath** [comment]
@KDuerden So, the code to do this is definitely live, and it looks like it's ordered by max_award_date descending apart from Lottery and SCVO. Which is odd. 

@BibianaC can you take a look at this when you get a chance? I've checked that the latest code is deployed on the server and I can't see why the code would behave differently in either of those cases. SCVO has one file that's invalid that I can understand might mess with ordering, but all the Lottery data seems fine. 

https://console.cloud.google.com/storage/browser/datagetter-360giving-output/branch/master/?project=datagetter-360giving&organizationId=980843748997 is the bucket with the raw data if, like me, you don't have it bookmarked.

**Comment by KDuerden** [comment]
Heart of England, John Moores and Seafarers UK are also out of order if based on max award date.

**Comment by BibianaC** [comment]
@robredpath @KDuerden The problem is that the sorting is done by year without taking in account the month. We will have to fix that.

**Comment by BibianaC** [comment]
@KDuerden we have fixed a few publishers but SCVO and the Heart of England are still not correct.

We will investigate further in the next non-sprint slot. I have one after the Cove 360 sprint.

**Comment by KDuerden** [comment]
Thank you, and that's fine. Heart of England looks in order to me now. With SCVO potentially a json thing?

**Comment by BibianaC** [comment]
@KDuerden I think we need to check properly why these two are not correct.

**Comment by BibianaC** [comment]
The order is now correct.
