### ISSUE TITLE
Registry update doesn't update details for Big Lottery Fund 100mb file

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/registry#44]
The Big Lottery Fund name has changed to The National Lottery Community Fund. I've made the amendments to the name and the data links on the registry and refreshed via data getter. The registry has updated but the 00MB file still says Big Lottery Fund. 
What is the process for updating this? Can that be run as soon as possible?

**Comment by robredpath** [comment]
@KDuerden We hardcode the results for the 100MB file. I updated the hardcoded results this week and the registry now shows the correct details.
