### ISSUE TITLE
new publisher listed out of alphabetical order

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/registry#47]
Trussell Trust is the latest publisher to share data. They appear in their alphabetical position in the daily data test but at the bottom in the Registry, below Zing.
They do style their name with lowercase the - could that have an impact?

**Comment by KDuerden** [comment]
I edited the name to give an upper case T in the and they appear as expected. 
I will have to re-instate the lowercase t because it's their brand, in time for GrantNav load next week.

**Comment by robredpath** [comment]
@KDuerden great spot - #48 fixes that and hopefully we can get it merged shortly

**Comment by robredpath** [comment]
@KDuerden #48 has been merged and will be autodeployed overnight. If you update Salesforce tomorrow it should all work as expected!

**Comment by robredpath** [comment]
@KDuerden is this now working as expected for you? Can we close this issue?

**Comment by KDuerden** [comment]
No, the Trussell Trust is still at the bottom

**Comment by robredpath** [comment]
@KDuerden ah ha - there was another deploy step that I missed. Deployed now, and it looks good on the live registry

**Comment by KDuerden** [comment]
confirmed and closing
