### ISSUE TITLE
Salesforce login email is hardcoded

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/registry#60]
Might be useful to be able to change this at some point

https://github.com/ThreeSixtyGiving/registry/blob/7397278b503c90ffd0f7616dba5b14e43a11664f/registry/salesforce.py#L9

**Comment by BibianaC** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Salesforce login email is hardcoded](https://trello.com/c/9FSdx7Qd/136-salesforce-login-email-is-hardcoded)

**Comment by BibianaC** [comment]
@drkane this has been done now.

**Comment by drkane** [comment]
Thanks for doing it so quickly @BibianaC ! That's great.
