### ISSUE TITLE
User story #7 - Give feedback 

### ISSUE THREAD

**Issue by morchickit** [ThreeSixtyGiving/registry#7]
As a publisher I want to know when I got feedback so we can improve the data.

**Comment by stevieflow** [comment]
This is a very similar description as #8 

> As a publisher I want to know when I got feedback so I can answer it and improve the data.

We would be best to understand the workflow around this exchange of feedback, and whether this would be 100% open/in public (or not)

**Comment by morchickit** [comment]
I need to refine this with @KDuerden

**Comment by morchickit** [comment]
As a publisher I want users to give feedback on the file that only I can see so we can improve the dataset. 

We want to signpost to an email  / contact page of the publisher.

**Comment by robredpath** [comment]
@kindly this probably is relevant to your research into what should be present in metadata
