### ISSUE TITLE
Selecting a publisher sometimes displays 2 publishers

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/registry#83]
**Bug:**

Sometimes when you select a Publisher in the dropdown the Dashboard displays more than the 1 selected

**Repro steps:**

If you select Sport England, the Dashboard displays Sport England and The Segelman Trust

**Screenshot:** 

![image](https://user-images.githubusercontent.com/82958988/141283048-43040bca-5c56-4470-a6c8-5f97d97b34a6.png)

**Comment by KDuerden** [comment]
I think this is fixed? It isn't happening anymore with the examples we saw previously.

**Comment by mariongalley** [comment]
Yeah I think this is fixed. Closing.
