### ISSUE TITLE
Licence: Unknown

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/registry#84]
**Description:**

On Individual Publisher pages in the Dashboard, Licence is listed as Unknown, but this is incorrect as they all have a licence

**Repro steps:**

Got to Dashboard > Publishers > Select any publisher > Click See More > Scroll down to the datasets > Bottom right corner of each dataset it says "Licence Unknown"

**Screenshot:**
![image](https://user-images.githubusercontent.com/82958988/141293309-17469ea3-99f3-43df-bb72-7694c9357c2c.png)

**Comment by KDuerden** [comment]
The Dashboard includes the name of the license but not the icon for all the types of license in use.

For example - Open Gov license

![image](https://user-images.githubusercontent.com/20462640/182824991-39cad92a-6b7b-479c-af20-910876ac0e31.png)

Same entry
![image](https://user-images.githubusercontent.com/20462640/182825068-2ca9c222-483f-48b1-a8a3-fb3a2ef80a68.png)

Similarly it looks like Public Domain logo isn't showing correctly either

![image](https://user-images.githubusercontent.com/20462640/182825289-715ba2f0-7559-4ddb-8404-78214d45eea7.png)

vs

![image](https://user-images.githubusercontent.com/20462640/182825339-4f9c1633-5387-4131-8cf1-62fdc454776b.png)

The preferred behaviour is to mirror the Data Registry design and icons.
