### ISSUE TITLE
Grants published/awarded heat map doesn't display 2022 grants

### ISSUE THREAD

**Issue by KDuerden** [ThreeSixtyGiving/registry#91]
There are already a few funders with grants awarded in 2022 but these aren't showing the heat maps.

For example

http://dashboard.360dashboard.vs.mythic-beasts.com/publisher/360G-esmeefairbairn

![image](https://user-images.githubusercontent.com/20462640/152391061-7b30f8cb-d681-42ed-8c0c-bccfbfaeb42a.png)

They have already made [22 grants](https://grantnav.threesixtygiving.org/search?query=%2A&default_field=%2A&sort=_score+desc&fundingOrganization=GB-CHC-200051&awardDate=2022)

It looks like the chart might be hard coded with the 2011 to 2021 segments.

Also can this chart be renamed from 

Total grants awarded to **Total grants published**

**Comment by michaelwood** [comment]
Leaving this open as we need to fix this programatically rather than defined in  https://github.com/ThreeSixtyGiving/registry/blob/dashboard/registry-vue/src/components/generic/awardYears.js file

**Comment by KDuerden** [comment]
It would be good to get a programmatic fix for the heat maps sorted out, as part of iterative improvements.

**Comment by Lathrisk** [comment]
@KDuerden @mariongalley 
I've updated the code such that the most recent year is the current year, and data is generated for 12 years previous, as well as an entry for all data before the 12th year prior.

So in this instance the most recent year is 2022, the earliest year is 2011, and an additional entry exists for "Older data".

The number of previous years can be easily changed. I think 12 fits in terms of page spacing, but it might not be significantly beneficial over 10, or 8 (below is a screenshot of 12 years of data).

![years-data](https://user-images.githubusercontent.com/517804/181289555-3f54467d-94c0-441f-9958-72770d46ca9f.png)

**Comment by mariongalley** [comment]
Fantastic, thanks @Lathrisk

**Comment by KDuerden** [comment]
Thanks that is really great. The publisher detail page explains that it shows past 10 years + aggregated years, so it would be good to stick with 10 + 1 (but if people disagree, we'll need to update that text)

![image](https://user-images.githubusercontent.com/20462640/181294589-eebe6bf9-7d5c-458f-b757-58835bfd85dd.png)

**Comment by mariongalley** [comment]
Good point - I think 10 years seems more 'logical', but I think 11 years looks good in terms of spacing. Not sure either is a great reason to prefer one over the other 😆 I'd be inclined to opt for 10 years + older?

**Comment by Lathrisk** [comment]
This has now been deployed.
