### ISSUE TITLE
Features not included and determination of whether in month/year badge is included

### ISSUE THREAD

**Issue by michaelwood** [ThreeSixtyGiving/registry#92]
"If a publishers data has the 1 year and/or 3 month badges in This data includes these features section, they are also repeated in the This data does not include these features section too.

https://qualitydashboard.threesixtygiving.org/publisher/360G-ATJF
https://qualitydashboard.threesixtygiving.org/publisher/360G-tnlcomfund

(via @KDuerden )

fixing hint: This is likely because the date calculation isn't a simple true/false evaluation so logical condition is evaluating the presence of the date delta output rather than it being in a range.

**Comment by KDuerden** [comment]
Is it possible to rationalise these badges, so only one is displayed in the includes / excludes sections?

**Comment by codemacabre** [comment]
@michaelwood Is this still an issue? I can't seem to reproduce it.
